### ISSUE TITLE
QuickIOPath.IsRootShareUnc returns true for any UNC share path, not just root UNC share path

### ISSUE THREAD

**Issue by Invisibility** [SchwabenCode/QuickIO#10]
The QuickIOPath.IsRootShareUnc function in QuickIOPath.Root.cs does not check that there is only server name and share name in path and nothing following it. The QuickIOPath.IsRootShareRegular does it correctly.

**Comment by BenjaminAbt** [comment]
Could you please provide a sample path
Otherweise I would guess u mean `\\server\share` and this is already covered
`[InlineData( @"\\server\share", false )]`
`[InlineData( @"\\server\share\", false )]`

`[InlineData( @"\\?\UNC\server\share", true )]`
`[InlineData( @"\\?\UNC\server\share\", true )]`

So it is hard to understand your issue.

**Comment by Invisibility** [comment]
Sorry for late reply. The issue is that `\\?\UNC\server\share\dir1` returns true, when the path is not a root.

**Comment by BenjaminAbt** [comment]
Fixed with https://github.com/SchwabenCode/QuickIO/commit/c96a4ce2f00b3970bcc6d68f4bfdad593fd2e7f0
