### ISSUE TITLE
Getting parent directory of a folder in C:\ returned my temp directory

### ISSUE THREAD

**Issue by wtyneb** [SchwabenCode/QuickIO#15]
`QuickIODirectoryInfo("""C:\some_folder""").Parent.FullNameUnc`
and
`QuickIODirectoryInfo("""C:\some_folder""").Parent.FullName`
returned the following directory
`"\\?\C:\Users\my_user_folder\AppData\Local\Temp"`
and
`"C:\Users\my_user_folder\AppData\Local\Temp"`

interestingly 
`QuickIODirectoryInfo("""C:\some_folder""").ParentFullName`
returned the correct directory
`"C:"`

**Comment by BenjaminAbt** [comment]
Which version do you exactly use?

**Comment by BenjaminAbt** [comment]
Bug is verified and will be fixed with new QuickIO Engine.
