### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by marius-stanescu-archive360** [SchwabenCode/QuickIO#19]
When trying to use the NuGet package in .NET Core application, you get the following warning: 

> Package 'QuickIO.NET 2.6.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

Could you please add support for .NET Core?

**Comment by BenjaminAbt** [comment]
No, because .NET Core does not offer OS-related APIs like Win32. Sorry.
It would only work with Desktop Pack.
