### ISSUE TITLE
Enumerating result of EnumerateFiles("*.ext") throws an exception when directory is empty

### ISSUE THREAD

**Issue by shayanelhami** [SchwabenCode/QuickIO#2]
Having this:

```
var files = folder.EnumerateFiles("*.ext");
```

And then doing anything with `files` (like `foreach` or `.Any()`) will throw an exception with message "The system cannot find the file specified."

This is, however, not the case if search pattern is not specified or `*.*` is used. It only happens when a file extension is specified in the search pattern (like `*.ext` here)

**Comment by BenjaminAbt** [comment]
EnumerateFiles just returns an IEnumerable and does not execute something.

On call "files" like any or foreach does, the execution starts and then an exception could be thrown like here.

So does your folder exist?

**Comment by shayanelhami** [comment]
Yes, the folder exists but "empty"

**Comment by BenjaminAbt** [comment]
Ok I'll check that the next days.

**Comment by BenjaminAbt** [comment]
Fixed with 3.0

**Comment by phrkdll** [comment]
Any plans on releasing version 3.0 soon? ;-)

**Comment by BenjaminAbt** [comment]
Based of the development of the .NET ecosystem I don't want to make a statement if there will be a 3.0.
The current code base is not suitable for the Modern Desktop and the future .NET.

Apart from that I honestly don't have any time for my .NET Framework libraries at the moment.
Pull requests are welcome, tho.
