### ISSUE TITLE
Heap corruption in QuickIOFileSystemSecurity.ReceiveFileSystemSecurityInformation

### ISSUE THREAD

**Issue by Invisibility** [SchwabenCode/QuickIO#9]
ReceiveFileSystemSecurityInformation calls GetNamedSecurityInfo, which returns memory points to pSecurityDescriptor, zeroHandle and sidHandle. However, only the memory in pSecurityDescriptor should be freed. The memory in zeroHandle and sidHandle simply point to memory in pSecurityDescriptor and must not be freed.

From MSDN, [https://msdn.microsoft.com/en-us/library/windows/desktop/aa446645(v=vs.85).aspx](url)

> If any of the ppsidOwner, ppsidGroup, ppDacl, or ppSacl parameters are non-NULL, and the SecurityInfo parameter specifies that they be retrieved from the object, those parameters will point to the corresponding parameters in the security descriptor returned in ppSecurityDescriptor.

**Comment by BenjaminAbt** [comment]
Thank you for your response. Already have this on my bucket list due to an email 6 weeks ago.
At this point I have not started to refactor the security stuff but I will fix that during the changes for 3.0.

**Comment by BenjaminAbt** [comment]
Fixed with 2.10.
